# Feel free to disable non-critical HA parts during devel by commenting out
# Generated in hadk by executing: cd $ANDROID_ROOT; rpm/helpers/add_new_device.sh

Description: Pattern with packages for i9305 configurations
Name: jolla-configuration-i9305
Requires:
- pattern:jolla-hw-adaptation-i9305
- pattern:jolla-configuration-sfe

Summary: Jolla Configuration i9305

